/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface StubTileContractInterface extends ethers.utils.Interface {
  functions: {
    "tileABI()": FunctionFragment;
    "tileDescription()": FunctionFragment;
    "tileEmoji()": FunctionFragment;
    "tileName()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "tileABI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tileDescription",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tileEmoji", values?: undefined): string;
  encodeFunctionData(functionFragment: "tileName", values?: undefined): string;

  decodeFunctionResult(functionFragment: "tileABI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tileDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tileEmoji", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tileName", data: BytesLike): Result;

  events: {};
}

export class StubTileContract extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: StubTileContractInterface;

  functions: {
    tileABI(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileABI()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tileDescription(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileDescription()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tileEmoji(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tileName(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileName()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  tileABI(overrides?: CallOverrides): Promise<string>;

  "tileABI()"(overrides?: CallOverrides): Promise<string>;

  tileDescription(overrides?: CallOverrides): Promise<string>;

  "tileDescription()"(overrides?: CallOverrides): Promise<string>;

  tileEmoji(overrides?: CallOverrides): Promise<string>;

  "tileEmoji()"(overrides?: CallOverrides): Promise<string>;

  tileName(overrides?: CallOverrides): Promise<string>;

  "tileName()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    tileABI(overrides?: CallOverrides): Promise<string>;

    "tileABI()"(overrides?: CallOverrides): Promise<string>;

    tileDescription(overrides?: CallOverrides): Promise<string>;

    "tileDescription()"(overrides?: CallOverrides): Promise<string>;

    tileEmoji(overrides?: CallOverrides): Promise<string>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<string>;

    tileName(overrides?: CallOverrides): Promise<string>;

    "tileName()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tileABI(overrides?: CallOverrides): Promise<BigNumber>;

    "tileABI()"(overrides?: CallOverrides): Promise<BigNumber>;

    tileDescription(overrides?: CallOverrides): Promise<BigNumber>;

    "tileDescription()"(overrides?: CallOverrides): Promise<BigNumber>;

    tileEmoji(overrides?: CallOverrides): Promise<BigNumber>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<BigNumber>;

    tileName(overrides?: CallOverrides): Promise<BigNumber>;

    "tileName()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    tileABI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileABI()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tileDescription(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileDescription()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tileEmoji(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tileName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
