/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TinyFarmLandInterface extends ethers.utils.Interface {
  functions: {
    "getClosestSelf()": FunctionFragment;
    "harvest()": FunctionFragment;
    "plant(string)": FunctionFragment;
    "tileABI()": FunctionFragment;
    "tileDescription()": FunctionFragment;
    "tileEmoji()": FunctionFragment;
    "tileName()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getClosestSelf",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "harvest", values?: undefined): string;
  encodeFunctionData(functionFragment: "plant", values: [string]): string;
  encodeFunctionData(functionFragment: "tileABI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tileDescription",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tileEmoji", values?: undefined): string;
  encodeFunctionData(functionFragment: "tileName", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getClosestSelf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tileABI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tileDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tileEmoji", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tileName", data: BytesLike): Result;

  events: {};
}

export class TinyFarmLand extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TinyFarmLandInterface;

  functions: {
    getClosestSelf(overrides?: Overrides): Promise<ContractTransaction>;

    "getClosestSelf()"(overrides?: Overrides): Promise<ContractTransaction>;

    harvest(overrides?: Overrides): Promise<ContractTransaction>;

    "harvest()"(overrides?: Overrides): Promise<ContractTransaction>;

    plant(
      _farmType: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "plant(string)"(
      _farmType: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    tileABI(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileABI()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tileDescription(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileDescription()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tileEmoji(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tileName(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "tileName()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  getClosestSelf(overrides?: Overrides): Promise<ContractTransaction>;

  "getClosestSelf()"(overrides?: Overrides): Promise<ContractTransaction>;

  harvest(overrides?: Overrides): Promise<ContractTransaction>;

  "harvest()"(overrides?: Overrides): Promise<ContractTransaction>;

  plant(_farmType: string, overrides?: Overrides): Promise<ContractTransaction>;

  "plant(string)"(
    _farmType: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  tileABI(overrides?: CallOverrides): Promise<string>;

  "tileABI()"(overrides?: CallOverrides): Promise<string>;

  tileDescription(overrides?: CallOverrides): Promise<string>;

  "tileDescription()"(overrides?: CallOverrides): Promise<string>;

  tileEmoji(overrides?: CallOverrides): Promise<string>;

  "tileEmoji()"(overrides?: CallOverrides): Promise<string>;

  tileName(overrides?: CallOverrides): Promise<string>;

  "tileName()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getClosestSelf(
      overrides?: CallOverrides
    ): Promise<{ x: BigNumber; y: BigNumber; 0: BigNumber; 1: BigNumber }>;

    "getClosestSelf()"(
      overrides?: CallOverrides
    ): Promise<{ x: BigNumber; y: BigNumber; 0: BigNumber; 1: BigNumber }>;

    harvest(overrides?: CallOverrides): Promise<void>;

    "harvest()"(overrides?: CallOverrides): Promise<void>;

    plant(_farmType: string, overrides?: CallOverrides): Promise<void>;

    "plant(string)"(
      _farmType: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tileABI(overrides?: CallOverrides): Promise<string>;

    "tileABI()"(overrides?: CallOverrides): Promise<string>;

    tileDescription(overrides?: CallOverrides): Promise<string>;

    "tileDescription()"(overrides?: CallOverrides): Promise<string>;

    tileEmoji(overrides?: CallOverrides): Promise<string>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<string>;

    tileName(overrides?: CallOverrides): Promise<string>;

    "tileName()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getClosestSelf(overrides?: Overrides): Promise<BigNumber>;

    "getClosestSelf()"(overrides?: Overrides): Promise<BigNumber>;

    harvest(overrides?: Overrides): Promise<BigNumber>;

    "harvest()"(overrides?: Overrides): Promise<BigNumber>;

    plant(_farmType: string, overrides?: Overrides): Promise<BigNumber>;

    "plant(string)"(
      _farmType: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    tileABI(overrides?: CallOverrides): Promise<BigNumber>;

    "tileABI()"(overrides?: CallOverrides): Promise<BigNumber>;

    tileDescription(overrides?: CallOverrides): Promise<BigNumber>;

    "tileDescription()"(overrides?: CallOverrides): Promise<BigNumber>;

    tileEmoji(overrides?: CallOverrides): Promise<BigNumber>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<BigNumber>;

    tileName(overrides?: CallOverrides): Promise<BigNumber>;

    "tileName()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getClosestSelf(overrides?: Overrides): Promise<PopulatedTransaction>;

    "getClosestSelf()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    harvest(overrides?: Overrides): Promise<PopulatedTransaction>;

    "harvest()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    plant(
      _farmType: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "plant(string)"(
      _farmType: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    tileABI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileABI()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tileDescription(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileDescription()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tileEmoji(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileEmoji()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tileName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tileName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
